# Generated by Django 5.1.4 on 2024-12-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=220)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Topic', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
